"""
Public Pydantic schema exports for the MoneyView API.

`apps.api.models.schemas` remains the stable import surface while the actual
definitions are split into smaller modules under `apps.api.models.schema_parts`.
"""

from .schema_parts.common import (
    APIMeta,
    APIResponse,
    ComparisonUniverseEnum,
    PeriodEnum,
    SentimentEnum,
)
from .schema_parts.corporate import (
    CorporateCompany,
    CorporateComparisonHistoryPoint,
    CorporateComparisonHistoryResponse,
    CorporateComparisonResponse,
    CorporateComparisonRow,
    CorporateComparisonSnapshotMeta,
    CorporateComparisonStockHistoryPoint,
    CorporateComparisonStockHistoryResponse,
    CorporateMetrics,
    RiskAssumptions,
    ValuationAssumptions,
)
from .schema_parts.market import DeltaBadge, IndicatorRecord, IndexQuote, StockOHLCV
from .schema_parts.news import MonteCarloResult, NewsArticle, TechnicalIndicators
from .schema_parts.portfolio_reporting import (
    RECONCILIATION_TOLERANCE,
    WEIGHT_SUM_TOLERANCE,
    AttributionDataContract,
    AttributionDataQuality,
    AttributionEffects,
    AttributionMetadata,
    AttributionMethodEnum,
    AttributionRequest,
    AttributionResult,
    AttributionTotals,
    BenchmarkDefinition,
    BenchmarkWeightsSourceEnum,
    PortfolioInput,
    RebalancingEnum,
    ReportExportFormatEnum,
    ReportExportRequest,
    ReportExportResponse,
    ReportFilters,
    ReportOptions,
    ReportPayload,
    ReportSummaryRequest,
    ReturnFrequencyEnum,
    RiskMethodEnum,
    RiskMetrics,
    RiskProfileInput,
    SectorAttribution,
)
from .schema_parts.watchlist import (
    PortfolioStock,
    WatchlistItem,
    WatchlistResyncResult,
    WatchlistSyncResult,
    WatchlistSyncStatus,
)

__all__ = [
    "APIMeta",
    "APIResponse",
    "ComparisonUniverseEnum",
    "PeriodEnum",
    "SentimentEnum",
    "CorporateCompany",
    "CorporateComparisonHistoryPoint",
    "CorporateComparisonHistoryResponse",
    "CorporateComparisonResponse",
    "CorporateComparisonRow",
    "CorporateComparisonSnapshotMeta",
    "CorporateComparisonStockHistoryPoint",
    "CorporateComparisonStockHistoryResponse",
    "CorporateMetrics",
    "RiskAssumptions",
    "ValuationAssumptions",
    "DeltaBadge",
    "IndicatorRecord",
    "IndexQuote",
    "StockOHLCV",
    "MonteCarloResult",
    "NewsArticle",
    "TechnicalIndicators",
    "RECONCILIATION_TOLERANCE",
    "WEIGHT_SUM_TOLERANCE",
    "AttributionDataContract",
    "AttributionDataQuality",
    "AttributionEffects",
    "AttributionMetadata",
    "AttributionMethodEnum",
    "AttributionRequest",
    "AttributionResult",
    "AttributionTotals",
    "BenchmarkDefinition",
    "BenchmarkWeightsSourceEnum",
    "PortfolioInput",
    "RebalancingEnum",
    "ReportExportFormatEnum",
    "ReportExportRequest",
    "ReportExportResponse",
    "ReportFilters",
    "ReportOptions",
    "ReportPayload",
    "ReportSummaryRequest",
    "ReturnFrequencyEnum",
    "RiskMethodEnum",
    "RiskMetrics",
    "RiskProfileInput",
    "SectorAttribution",
    "PortfolioStock",
    "WatchlistItem",
    "WatchlistResyncResult",
    "WatchlistSyncResult",
    "WatchlistSyncStatus",
]
